import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThirdwebProvider } from "../lib/thirdweb";
import Navbar from "../components/Header/navbar";
import Footer from "../components/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative max-w-[100vw] overflow-x-hidden">
          <ThirdwebProvider>
            <Navbar />
            {children}
            <Footer />
          </ThirdwebProvider>
        </main>
      </body>
    </html>
  );
}
